# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mt9aTtzOChp23jg53KXay0Kh_XLOIn1F
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score

# load dataset
from google.colab import files
import io 
uploaded=files.upload()

# Read dataset
df=pd.read_csv(io.BytesIO(uploaded['Salary_Data.csv']))

# Plot 5 first line of dataset
df.head(10)

# plot data
#plt.scatter(df.YearsExperience,df.Salary)
plt.scatter(df['YearsExperience'],df['Salary'], color='blue')
plt.show()

# Build linear regression 
model = linear_model.LinearRegression()

# Prepare training dataset
X=pd.DataFrame(df.iloc[:,0])
y=df.iloc[:,1] # Similar to the upper line just shorter
#print(X,y)
#print(Y) 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)
#test_size => we train the model by 20 % of the element

# Plot length of the dataset training 
print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

# model train
model.fit(X_train,y_train)

# salary preidction  
y_pred=model.predict(X_test)

print(y_pred)
print(y_test)

print(r2_score(y_test,y_pred))

# Looking dataset 
plt.scatter(X,y,color='blue')
# y=ax + b 
y_pred2= model.predict(X) 
plt.plot(X,y_pred2,color='red')
plt.xlabel('experience years')
plt.ylabel('Salary')
plt.show()

