# -*- coding: utf-8 -*-
"""MultipleLinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z01B9bJi4IcLDnRLFupSfbDmoJHXu2C_
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score

# load dataset
from google.colab import files
import io 
uploaded=files.upload()

df=pd.read_csv(io.BytesIO(uploaded['50_Startups.csv']))

# Plot dataSet 
df.head(10)

# Creation of the model
model=LinearRegression()

# Prepare the test data and training test 
#X=df.iloc[:,0:3] 
X=df.iloc[:,:-2]
y=df.iloc[:,-1]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

print(X_train.shape, X_test.shape)
print(y_train.shape, y_test.shape)

# Model trainning 
model.fit(X_train,y_train)

# Prevision 
y_pred=model.predict(X_test)
y_pred

# Prevision comparision y_pred
comp=pd.DataFrame(y_pred,y_test)
comp

print(r2_score(y_test,y_pred))

