# -*- coding: utf-8 -*-
"""LogisticRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10GhX58GYiB0dm-D4Cm98Lk4rUmajemcy
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

# load dataset
from google.colab import files
import io 
uploaded=files.upload()

df=pd.read_csv(io.BytesIO(uploaded['LogisticsSocial_Network_Ads.csv']))

df.head()

data=df.iloc[:,1:3]
y=df.iloc[:,-1]
#data.head()
#y.head()

data['Gender']=data['Gender'].replace({'Female':0,'Male':1})

data.head()

# Prepare the test data and training test 
#X=df.iloc[:,0:3] 
X=data.values
y=df.iloc[:,-1].values
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=LogisticRegression()

# Model trainning 
model.fit(X_train,y_train)

# Prevision 
y_pred=model.predict(X_test)

# Prevision comparision y_pred
comp=pd.DataFrame(y_pred,y_test)
comp

print('Accuracy score is ', accuracy_score(y_test,y_pred))

# Confusion matrix 
print("Confusion matrix is", confusion_matrix(y_test,y_pred))

