# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJKrvIkCUpOOLtV3l2og1vJk9rx7qLl1
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

# load dataset
df = datasets.load_wine()

df.keys()

print(df.DESCR)

# Prepare the dataSet
X=df.data
y=df.target

print(X.shape,y.shape)

y

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train) # knn

y_pred=model.predict(X_test)

print("Precision :", accuracy_score(y_test,y_pred))

# Prevision comparision y_pred
comp=pd.DataFrame(y_pred,y_test)
comp

X

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled

X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=42)
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train) # knn 
y_pred=model.predict(X_test)
print("Precision :", accuracy_score(y_test,y_pred))

model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train) # knn 
y_pred=model.predict(X_test)
print("Precision :", accuracy_score(y_test,y_pred))

model=KNeighborsClassifier(n_neighbors=7)
model.fit(X_train, y_train) # knn 
y_pred=model.predict(X_test)
print("Precision :", accuracy_score(y_test,y_pred))