# -*- coding: utf-8 -*-
"""kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18yN3QYmnlJ6T6wInj4M28cuZb0TjyUXC
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn.cluster import KMeans 
#from sklearn.model_selection import StandardScaler
#from sklearn.metrics import accuracy_score
#from sklearn import datasets
from sklearn.preprocessing import StandardScaler

# load dataset
from google.colab import files
import io 
uploaded=files.upload()

df=pd.read_csv(io.BytesIO(uploaded['kmeans_Mall_Customers.csv']))

df.head()

X = df.iloc[:, [3, 4]].values

from sklearn.datasets import make_blobs

n_samples = 1500
random_state = 170
X, y = make_blobs(n_samples=n_samples, random_state=random_state)

y_pred = KMeans(n_clusters=2, random_state=random_state).fit_predict(X)

plt.subplot(221)
#plt.scatter(X[:, 0], X[:, 1], c=y_pred,cmap='viridis')
plt.scatter(X[:, 0], X[:, 1], c=y_pred)

plt.title("Incorrect Number of Blobs")

y_pred = KMeans(n_clusters=3, random_state=random_state).fit_predict(X)

plt.subplot(221)
plt.scatter(X[:, 0], X[:, 1], c=y_pred)
plt.title("correct Number of Blobs")

scaler=StandardScaler()
X_scaled= scaler.fit_transform(X)

X # X_scaled

X_scaled #

model=KMeans(n_clusters=3, random_state=42)
model.fit(X_scaled)

model.labels_

plt.subplot(221)
plt.scatter(X[:, 0], X[:, 1], c=model.labels_)
plt.title("correct Number of Blobs")