# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BV1nMdHvdOR69yyQ5UgItFJcv8WmMDgK
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
#from sklearn import datasets  
from sklearn.model_selection import train_test_split
from sklearn import metrics
#from sklearn.metrics import accuracy_score
#from sklearn import datasets
#from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

# load dataset
from google.colab import files
import io 
uploaded=files.upload()

df1=pd.read_csv(io.BytesIO(uploaded['PastHires.csv']))

df1.head(10)

# Prepare dataset
df1['Level of Education'].value_counts()

import copy
df =  copy.deepcopy(df1)

d1={'Y':1,'N':0}
d2={'BS':1,'MS':2,'PhD':3}
df['Employed?']=df['Employed?'].map(d1)
df['Top-tier school']=df['Top-tier school'].map(d1)
df['Interned']=df['Interned'].map(d1)
df['Level of Education']=df['Level of Education'].map(d2)
#df['Previous employers']=df['Previous employers'].map(d2)
df['Hired']=df['Hired'].map(d1)
df.head(10)

# Model creation
model=RandomForestClassifier(n_estimators=1000,random_state=42)

#Prepare train and test dataset  
X=df.iloc[:,:-1]
y=df.iloc[:,-1]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

# model apply
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print('precision is', metrics.accuracy_score(y_test,y_pred))



# Random forest