# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-xbF-HxHINdB2dn2PFfYMX1wkRh5L1wq
"""

# Packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Machine learning packages
from sklearn import datasets, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm

# Load dataSet
df=datasets.load_breast_cancer()

df.keys()

df.DESCR

X=df.data
y=df.target

#Standardisation des données

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_train, X_test,y_train,y_test = train_test_split(X_scaled,y,test_size = 0.2, random_state=42)

# model creation
model=svm.SVC(kernel='linear')

model.fit(X_train,y_train)

y_pred=model.predict(X_test)

# compare 
comp=pd.DataFrame(y_pred,y_test)
comp

print('Model precision',metrics.accuracy_score(y_test,y_pred))

print('Confusion matrix', metrics.confusion_matrix(y_test,y_pred))

# model creation
model=svm.SVC(kernel='poly',degree=1,gamma=100) 
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print('Model precision',metrics.accuracy_score(y_test,y_pred))

# model creation
model=svm.SVC(kernel='sigmoid',degree=200,C=0.2) 
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print('Model precision',metrics.accuracy_score(y_test,y_pred))